### ISSUE TITLE
Player not getting added to RawPlayers

### ISSUE THREAD

**Issue by econoraptor** [EHVAG/demoinfo#93]
I noticed that player_hurt and player_death events were sending a null Player in the eventargs, and I figured out that the player with the corresponding userid isn't ever being added to RawPlayers.

The fact that null is explicitly sent rather than raising an exception leads me to think that there is a known gap where events can be sent for players who haven't been added yet.  I wanted to be sure this was known though, and I was also hoping someone could give a bit of an explanation.  Thanks.

Here's a link to the demo where it's happening -- the d2 match: http://www.hltv.org/interfaces/download.php?demoid=19733

edit: When I play the demo the name of the victim doesn't show in the upper right when killed, so it's probably a bug with the demo itself.  Kind of strange because he's clearly fully loaded into the game -- running around and everything.

**Comment by moritzuehling** [comment]
> When I play the demo the name of the victim doesn't show in the upper right when killed, so it's probably a bug with the demo itself. Kind of strange because he's clearly fully loaded into the game -- running around and everything.

PlayerInfos (username + steamid) are stored in string-tables, the players position and other stuff is stored in entities. 

It can be that there are inconsistencies within a demofile. 

This parser only supports demos that are displayed correctly within CS:GO, because everything else would be lunatic in my opinion. So I can only advise to work around that bug :/
